name: pr-main
on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto Pull Request
          title: Changes by Pull Request Main action
          body: Auto-created Pull Request
          branch: ${{ github.ref }}
          base: main
          labels: ready to merge
